# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True, help_text='What is it?')),
                ('symptoms', models.TextField(blank=True, help_text='Common symptoms (can use bullet points)')),
                ('procedure_details', models.TextField(blank=True, help_text='Treatment process / why early diagnosis')),
                ('benefits', models.TextField(blank=True)),
                ('why_choose_us', models.TextField(blank=True, help_text='Why choose this hospital for this treatment')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='treatments/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('treatment', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='faqs', to='treatments.treatment')),
            ],
            options={
                'ordering': ['display_order', 'question'],
                'verbose_name': 'Treatment FAQ',
                'verbose_name_plural': 'Treatment FAQs',
            },
        ),
    ]
